name: danp04
title: "How to build a community of tech writers in your country"
description: An example of technical documentation hosted on Github pages, using the Feeling responsive Jekyll theme.
remote_theme: danp04/feeling-responsive
url: 'https://danp04.github.io'
baseurl: '/Test2'
urlimg: 'https://danp04.github.io/Test2/images/'
logo: "log.png"

aux_links:
  "Source repository on GitHub":
    - "//github.com/danp04/danp04.github.io/Test2"

plugins:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate

markdown           : kramdown
permalink          : /:categories/:title/
highlight          : rouge
include            : ['.htaccess']

language: 'en'

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

defaults:
  -
    scope:
      path: ''
      type: "pages"
    values:
      show_meta: false 
      sidebar: 
      comments: false

  -
    scope:
      path: ''
      type: "posts"
    values:
      show_meta: true
      sidebar:
      comments: false

sass:
    sass_dir : _sass
    style    : :compressed


back_to_top: "true"
back_to_top_text: "Back to top"
